FROM centos:centos7

MAINTAINER Tharcísio Angelo <tharcisio.angelo@yahoo.com.br>

ENV JAVA_HOME=/usr/lib/jvm/jre-openjdk
ENV TARGET=file:///root

RUN \
  yum install -y epel-release && \
  yum install -y                 \
    java-1.7.0-openjdk           \
    unzip                     && \
  rm -rf /var/cache/yum       && \
  rm -rf /var/lib/yum/yumdb

COPY ["*.sh", "/root/"]
WORKDIR /root
